// ---------------------------------------------------------------------------
// Shared TypeScript types cho toàn bộ frontend
// ---------------------------------------------------------------------------

/** Severity levels cho code review issues. */
export type Severity = "critical" | "high" | "medium" | "low" | "info";

/** Difficulty levels cho exam questions. */
export type Difficulty = "easy" | "medium" | "hard";

/** Document status từ backend. */
export type DocumentStatus = "uploaded" | "processing" | "completed" | "failed";

/** Question generated by AI. */
export interface Question {
  id: number;
  question: string;
  hint: string;
  difficulty: Difficulty;
  persona: string;
}

/** Code issue found by AI review. */
export interface CodeIssue {
  id: number;
  type: string;
  file: string;
  line: number;
  description: string;
  severity: Severity;
  suggestion: string;
}

/** Report metric card. */
export interface Metric {
  label: string;
  value: string;
}
