"""
Fallback code reviewer — dùng khi AI gateway không phản hồi.

Trả về danh sách issue mặc định theo focus areas thay vì gọi AI.
Được gọi tự động khi circuit breaker mở.
"""
import logging
import re
from dataclasses import dataclass
from typing import Any, List

from app.services.code_scanner import ScannedFile

logger = logging.getLogger(__name__)


# Fallback comments theo từng category
FALLBACK_COMMENTS: dict[str, list[dict[str, str]]] = {
    "security": [
        {
            "description": "Kiểm tra input validation cho các API endpoints — đảm bảo sanitize toàn bộ user input.",
            "suggestion": "Sử dụng parameterized queries, validate đầu vào bằng pydantic hoặc validator.",
            "severity": "high",
        },
        {
            "description": "Đảm bảo không expose sensitive data (API keys, tokens, passwords) trong logs hoặc response.",
            "suggestion": "Sử dụng environment variables cho secrets, tắt debug logging trong production.",
            "severity": "high",
        },
        {
            "description": "Kiểm tra authentication và authorization cho các endpoint nhạy cảm.",
            "suggestion": "Dùng JWT token với expiration, check role-based access control (RBAC).",
            "severity": "medium",
        },
    ],
    "performance": [
        {
            "description": "Kiểm tra N+1 query problem trong database queries — đặc biệt với ORM queries có join.",
            "suggestion": "Sử dụng selectinload() hoặc joinedload() để eager loading, tránh query trong loop.",
            "severity": "medium",
        },
        {
            "description": "Cân nhắc caching cho các endpoints read-heavy (truy vấn thường xuyên).",
            "suggestion": "Dùng Redis cache với TTL cho dữ liệu ít thay đổi, cache invalidation khi write.",
            "severity": "low",
        },
        {
            "description": "Kiểm tra các query không có index phù hợp trên database tables.",
            "suggestion": "Thêm database index cho các column thường xuyên filter/sort/join.",
            "severity": "medium",
        },
    ],
    "style": [
        {
            "description": "Tuân thủ naming convention của project (PEP 8 cho Python, Google style cho TypeScript).",
            "suggestion": "Dùng pre-commit hooks với black, isort, ruff để tự động format code.",
            "severity": "low",
        },
        {
            "description": "Thêm type hints cho function parameters và return types.",
            "suggestion": "Sử dụng mypy để check type consistency, đặc biệt cho public APIs.",
            "severity": "low",
        },
        {
            "description": "Kiểm tra comment/docstring cho các functions phức tạp (>20 lines).",
            "suggestion": "Viết docstring theo Google/NumPy style, giải thích purpose và edge cases.",
            "severity": "info",
        },
    ],
    "logic_error": [
        {
            "description": "Kiểm tra edge cases: empty input, null values, boundary conditions.",
            "suggestion": "Thêm unit tests cho các edge cases, dùng pytest.raises cho exception cases.",
            "severity": "medium",
        },
        {
            "description": "Đảm bảo exception handling rõ ràng — không bắt chung chung Exception.",
            "suggestion": "Bắt specific exceptions, log error context, return user-friendly error messages.",
            "severity": "medium",
        },
        {
            "description": "Kiểm tra race conditions trong concurrent operations (database writes, file operations).",
            "suggestion": "Sử dụng database transactions, locks, hoặc queue system cho async operations.",
            "severity": "high",
        },
    ],
    "code_smell": [
        {
            "description": "Tìm các functions quá dài (>50 lines) — nên tách thành sub-functions.",
            "suggestion": "Áp dụng Single Responsibility Principle, mỗi function làm một việc.",
            "severity": "low",
        },
        {
            "description": "Kiểm tra duplicated code — các đoạn logic lặp lại nên thành functions chung.",
            "suggestion": "Tách thành utility functions, dùng composition thay vì copy-paste.",
            "severity": "medium",
        },
        {
            "description": "Cảnh báo các magic numbers/strings — nên đổi thành named constants.",
            "suggestion": "Định nghĩa constants ở module level, dùng Enums cho fixed sets of values.",
            "severity": "info",
        },
    ],
}


@dataclass
class FallbackIssue:
    """Issue generated by fallback reviewer."""
    type: str
    file: str
    line: int
    description: str
    severity: str
    suggestion: str
    is_fallback: bool = True


class FallbackCodeReviewer:
    """
    Generate code review comments when AI provider is unavailable.
    Uses predefined patterns and heuristics.
    """

    def __init__(self):
        self.issue_counter = 0

    def review_code(
        self,
        files: List[ScannedFile],
        focus_areas: List[str] | None = None,
    ) -> List[dict[str, Any]]:
        """
        Generate fallback review comments.

        Args:
            files: List of scanned code files
            focus_areas: Which categories to focus on (default: all)

        Returns:
            List of issue dicts (same format as AI review)
        """
        if focus_areas is None:
            focus_areas = list(FALLBACK_COMMENTS.keys())

        issues: List[dict[str, Any]] = []

        # 1. Add predefined fallback comments
        for area in focus_areas:
            comments = FALLBACK_COMMENTS.get(area, [])
            for comment in comments:
                self.issue_counter += 1
                issues.append({
                    "id": self.issue_counter,
                    "type": area,
                    "file": "general",
                    "line": 1,
                    "description": comment["description"],
                    "severity": comment["severity"],
                    "suggestion": comment["suggestion"],
                    "is_fallback": True,
                })

        # 2. Run heuristic scan on actual files
        heuristic_issues = self._heuristic_scan(files)
        issues.extend(heuristic_issues)

        logger.info(
            "Fallback reviewer generated %d issues for %d files",
            len(issues),
            len(files),
        )
        return issues

    def _heuristic_scan(self, files: List[ScannedFile]) -> List[dict[str, Any]]:
        """Run pattern-based heuristic scan on code files."""
        patterns = [
            (
                "security",
                "high",
                re.compile(r"(?i)\b(api[_-]?key|secret|password|token)\b\s*[:=]\s*['\"]([^'\"]+)['\"]"),
                "Phát hiện có thể hardcode secret hoặc credential trong source code.",
                "Di chuyển secret sang environment variables hoặc secret manager.",
            ),
            (
                "security",
                "high",
                re.compile(r"\b(eval|exec|os\.system|subprocess\.run)\s*\("),
                "Đoạn code thực thi lệnh động — potential code injection vulnerability.",
                "Hạn chế dùng execution động; nếu bắt buộc hãy validate input và sandbox chặt.",
            ),
            (
                "code_smell",
                "medium",
                re.compile(r"(?i)\b(TODO|FIXME|HACK)\b"),
                "Còn marker TODO/FIXME/HACK trong code — nên xử lý trước khi merge.",
                "Xử lý hoặc tạo ticket rõ ràng trước khi deploy.",
            ),
            (
                "code_smell",
                "info",
                re.compile(r"\b(console\.log|print)\s*\("),
                "Có debug log statement — có thể lộ thông tin nhạy cảm.",
                "Giữ logging có kiểm soát hoặc loại bỏ debug log trước khi release.",
            ),
            (
                "logic_error",
                "medium",
                re.compile(r"^\s*except\s*:\s*$|^\s*catch\s*\(\s*\)\s*\{", re.MULTILINE),
                "Bắt lỗi quá rộng — có thể che mất exception thật.",
                "Bắt exception cụ thể hơn và log rõ ngữ cảnh lỗi.",
            ),
        ]

        issues = []
        seen: set[tuple[str, int, str]] = set()

        for file in files:
            for line_number, line in enumerate(file.content.splitlines(), start=1):
                for issue_type, severity, pattern, description, suggestion in patterns:
                    if not pattern.search(line):
                        continue
                    key = (file.path, line_number, issue_type)
                    if key in seen:
                        continue
                    seen.add(key)
                    self.issue_counter += 1
                    issues.append({
                        "id": self.issue_counter,
                        "type": issue_type,
                        "file": file.path,
                        "line": line_number,
                        "description": description,
                        "severity": severity,
                        "suggestion": suggestion,
                        "is_fallback": True,
                    })

        return issues

    def get_summary(self, issues: List[dict[str, Any]]) -> str:
        """Generate human-readable summary of fallback issues."""
        total = len(issues)
        by_severity = {}
        for issue in issues:
            sev = issue.get("severity", "unknown")
            by_severity[sev] = by_severity.get(sev, 0) + 1

        parts = [f"Phát hiện {total} vấn đề từ fallback reviewer"]
        for sev, count in sorted(by_severity.items()):
            parts.append(f"{sev}: {count}")
        return ". ".join(parts) + "."


# Singleton instance
fallback_reviewer = FallbackCodeReviewer()
